config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'login#index', as: :login
  post 'login' => 'login#authenticate', as: :authenticate
  get 'logout' => 'login#logout', as: :logout
  get '/' => 'home#index', as: :home
  root 'home#index'

  resources :users
  resources :tasks
  resources :task_lists

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_list
  belongs_to :user

  validates :title, :priority, :due_date, presence: true
  validates :task_list, presence: {message: 'must be selected' }
  validates :priority, inclusion: { in: 1..10, message: 'must be a number between 1 and 10' }

  def to_s
    title
  end
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  has_many :tasks

  validates :name, :description, presence: true
	validates :name, uniqueness: true

  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :get_all_task_lists
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def get_all_task_lists
  	@all_task_lists = Array.new
  	TaskList.all.each do |item|
  		@all_task_lists.push(item)
  	end
  end

end

app/controllers/home_controller.rb
class HomeController < ProtectedController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end

  def authenticate
  	user = User.find_by_username(params[:username])
  	user2 = User.find_by_password(params[:password])
  	if user == user2 && !user.nil?
  		session[:user_id] = user.id
  		flash[:message] = "Logged in"
  		redirect_to root_url
  	else
  		flash[:message] = "Username/password not found"
  		redirect_to :back
  	end
  end

  def logout
  	session[:user_id] = nil
  	redirect_to login_path
  end
end

app/controllers/protected_controller.rb
class ProtectedController < ApplicationController
	before_action :require_login

	def require_login
		if session[:user_id].nil?
			flash[:message] = "User not logged in"
			redirect_to login_path
		end
	end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: [:show, :edit, :update, :destroy]

  # GET /task_lists
  # GET /task_lists.json
  def index
    @task_lists = TaskList.all
  end

  # GET /task_lists/1
  # GET /task_lists/1.json
  def show
  end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new
  end

  # GET /task_lists/1/edit
  def edit
  end

  # POST /task_lists
  # POST /task_lists.json
  def create
    @task_list = TaskList.new(task_list_params)

    respond_to do |format|
      if @task_list.save
        format.html { redirect_to @task_list, notice: 'Task list was successfully created.' }
        format.json { render :show, status: :created, location: @task_list }
      else
        format.html { render :new }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_lists/1
  # PATCH/PUT /task_lists/1.json
  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        format.html { redirect_to @task_list, notice: 'Task list was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_list }
      else
        format.html { render :edit }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1
  # DELETE /task_lists/1.json
  def destroy
    @task_list.destroy
    respond_to do |format|
      format.html { redirect_to task_lists_url, notice: 'Task list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_list_params
      params.require(:task_list).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :priority, :due_date, :is_complete, :task_list_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/protected_helper.rb
module ProtectedHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

<% user = User.find_by_id(session[:user_id]) %>
<h2>Tasks</h2>
<ul>

<% Task.all.each do |task| %>
	<% if task.user_id == user.id %>
		<li><%= task.title %></li>
	<% end %>
<% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoStarter</title>
  
  <%= stylesheet_link_tag 'site' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="header" id="header"></div>

	<div id="primary">
		<% if flash[:message] %>
		<p class="flash­message"><%= flash[:message] %></p>
		<% end %>
	</div>

	<div class="sidebar" id="sidebar">
		<ul>
			<% @all_task_lists.each do |list_item| %>
				<li><a href="/task_lists/<%=list_item.id%>"> <%= list_item.name %> </a></li>
			<% end %>
		</ul>
		<% if session[:user_id] %>
			<%= link_to 'Logout', logout_path %>
		<% else %>
			<%= link_to 'Login', login_path %>
		<% end %>
	</div>

<%= yield %>

<div class="footer" id="footer"></div>

</body>
</html>

app/views/layouts/todo_list.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoStarter</title>
  
  <%= stylesheet_link_tag 'site' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="header" id="header"></div>

	<div id="primary">
		<% if flash[:message] %>
		<p class="flash­message"><%= flash[:message] %></p>
		<% end %>
	</div>

	<div class="sidebar" id="sidebar">
		<ul>
			<% @all_task_lists.each do |list_item| %>
				<li><a href="/task_lists/<%=list_item.id%>"> <%= list_item.name %> </a></li>
			<% end %>
		</ul>
		<% if session[:user_id] %>
			<%= link_to 'Logout', logout_path %>
		<% else %>
			<%= link_to 'Login', login_path %>
		<% end %>
	</div>

<%= yield %>

<div class="footer" id="footer"></div>

</body>
</html>

app/views/login/authenticate.html.erb
<h1>Login#authenticate</h1>
<p>Find me in app/views/login/authenticate.html.erb</p>

app/views/login/index.html.erb
<h1>Login</h1>

<%= form_tag(authenticate_path) do %>

  <div class="field">
    <%= label_tag :username %><br>
    <%= text_field_tag :username %>
  </div>
  <div class="field">
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/login/logout.html.erb
<h1>Login#logout</h1>
<p>Find me in app/views/login/logout.html.erb</p>

app/views/task_lists/_form.html.erb
<%= form_for(@task_list) do |f| %>
  <% if @task_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
      <% @task_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_lists/edit.html.erb
<h1>Editing Task List</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_list %> |
<%= link_to 'Back', task_lists_path %>

app/views/task_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Task Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_lists.each do |task_list| %>
      <tr>
        <td><%= task_list.name %></td>
        <td><%= task_list.description %></td>
        <td><%= link_to 'Show', task_list %></td>
        <td><%= link_to 'Edit', edit_task_list_path(task_list) %></td>
        <td><%= link_to 'Destroy', task_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task list', new_task_list_path %>

app/views/task_lists/new.html.erb
<h1>New Task List</h1>

<%= render 'form' %>

<%= link_to 'Back', task_lists_path %>

app/views/task_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task_list.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task_list.description %>
</p>

<h2>Tasks</h2>

<ul>
  <% @task_list.tasks.each do | task | %>
    <li><%= task %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_task_list_path(@task_list) %> |
<%= link_to 'Back', task_lists_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :is_complete %><br>
    <%= f.check_box :is_complete %>
  </div>
  <div class="field">
    <%= f.label :task_list_id %><br>
    <%= f.collection_select :task_list_id, TaskList.all, :id, :name, prompt: 'Please select a task list' %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :first_name, prompt: 'No user assigned' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Priority</th>
      <th>Due date</th>
      <th>Is complete</th>
      <th>Task list</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.priority %></td>
        <td><%= task.due_date %></td>
        <td><%= task.is_complete %></td>
        <td><%= task.task_list %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<p>
  <strong>Is complete:</strong>
  <%= @task.is_complete %>
</p>

<p>
  <strong>Task list:</strong>
  <%= @task.task_list %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>